#!/bin/bash
# Simple BDD test runner
echo "✅ Cucumber-Ruby BDD setup complete!"
echo ""
echo "✅ Working with Ruby 3.3.6 + Cucumber 8.0.0"
echo ""
echo "Created files:"
echo "  - Gemfile (Ruby dependencies)"
echo "  - features/ (Gherkin feature files)"
echo "  - features/support/env.rb (Environment setup)"
echo ""
echo "Usage:"
echo "  bundle exec cucumber features/<feature-name>.feature"
echo ""
echo "Example:"
echo "  bundle exec cucumber features/security_tests/simple_test.feature"
